SmartPlanner/SmartPlanner/Controllers/SubCategoriesController.cs
using SmartPlanner.Attributes;
using SmartPlanner.BusinessLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static SmartPlanner.BusinessLayer.Common.Enums;

namespace SmartPlanner.Controllers
{
    [AuthenticateUserSession]
    public class SubCategoriesController : Controller
    {
        private SubCategoryService _subCatService = new SubCategoryService();
        
        private void SetConfigTablesValues(SubCategory subCategory)
        {
            subCategory.Categories = new ConfigurationTableValueService().ListByConfigId((int)EnumConfigurationTables.Category, true);
        }

        public ActionResult Index()
        {
            return View(_subCatService.GetList());
        }

        public ActionResult Detail(int? id)
        {
            SubCategory subCategory = new SubCategory();

            if (id.HasValue && id.Value > 0)
                subCategory = _subCatService.GetEntityById(id.Value);

            this.SetConfigTablesValues(subCategory);
            return View(subCategory);
        }

        [HttpPost]
        public ActionResult Detail(SubCategory subCategory)
        {
            try
            {
                this.SetConfigTablesValues(subCategory);
                if (!ModelState.IsValid)
                    return View(subCategory);
                bool isAdded = false;
                if (subCategory.Id == 0)
                    isAdded = true;
                if (!_subCatService.Save(subCategory) && !string.IsNullOrWhiteSpace(subCategory.BrokenBusinessRulesText))
                {
                    ModelState.AddModelError("", subCategory.BrokenBusinessRulesText);
                    return View(subCategory);
                }
                if (isAdded)
                {
                    ModelState.Clear();
                    ViewBag.Message = "Order Detail added successfully";

                    SubCategory newSubCategory = new SubCategory();
                    this.SetConfigTablesValues(newSubCategory);
                    return View(newSubCategory);
                }
                else
                {
                    ViewBag.Message = "Order Detail updated successfully";
                    return View(subCategory);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(subCategory);
            }
        }

        public ActionResult Delete(int id)
        {
            return View(_subCatService.GetEntityById(id));
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                _subCatService.DeleteById(id);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                if (ex.Message.StartsWith("The DELETE statement conflicted with the REFERENCE constraint"))
                    ModelState.AddModelError("", "Unable to delete this sub category as involved with some actions");
                return View(_subCatService.GetEntityById(id));
            }
        }
    }
}

SmartPlanner/SmartPlanner/Views/SubCategories/Delete.cshtml
@model SmartPlanner.BusinessLayer.SubCategory

@{
    ViewBag.Title = "Delete Sub Category";
}

<!-- Start Content-->
<div class="container-fluid">
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
                        <li class="breadcrumb-item active">@ViewBag.Title</li>
                    </ol>
                </div>
                <h4 class="page-title">@ViewBag.Title</h4>
            </div>
        </div>
    </div>

    <!-- end page title -->

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <h4 class="header-title">Are you sure you want to delete this?</h4>

                <!-- Start Display the message as a dismissable alert -->
                @if (!string.IsNullOrEmpty(@ViewBag.Message))
                {
                    <div class="alert alert-success alert-dismissible bg-success text-white border-0 fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        @ViewBag.Message
                    </div>
                }

                @if (!ViewData.ModelState.IsValid)
                {
                    <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        @Html.ValidationSummary(true)
                    </div>
                }

                <!-- End Display the message as a dismissable alert -->

                <div class="row">
                    <div class="col-lg-2">
                    </div>
                    <div class="col-lg-8">
                        @using (Html.BeginForm("Delete", "SubCategories", FormMethod.Post, htmlAttributes: new { @class = "needs-validation" }))
                        {

                            @Html.HiddenFor(model => model.Id)

                            <div class="form-group mb-3">

                                <dl class="row">
                                    <dt class="col-sm-3">
                                        @Html.DisplayNameFor(model => model.CategoryId)
                                    </dt>

                                    <dd class="col-sm-9">
                                        @Html.DisplayFor(model => model.Category.ConfigValue)
                                    </dd>

                                    <dt class="col-sm-3">
                                        @Html.DisplayNameFor(model => model.SubCategoryName)
                                    </dt>

                                    <dd class="col-sm-9">
                                        @Html.DisplayFor(model => model.SubCategoryName)
                                    </dd>

                                </dl>

                            </div>

                            <div class="form-group mb-0">
                                <input type="submit" class="btn btn-primary" value="Delete">
                                <a href="@Url.Action("Index", "SubCategories")" class="btn btn-outline-blue waves-effect waves-light" id="demo-delete-row"><i class="mdi mdi-account-multiple mr-1"></i>Go to Sub Category List</a>
                            </div>
                        }

                    </div>

                    <div class="col-lg-2">
                    </div>
                </div>

            </div> <!-- end card-box-->
        </div> <!-- end col-->
    </div>
    <!-- end row -->
</div>

SmartPlanner/SmartPlanner/Views/SubCategories/Detail.cshtml
@model SmartPlanner.BusinessLayer.SubCategory

@{
    if (Model == null || Model.Id > 0)
    {
        ViewBag.Title = "Update Sub Categoty";
        ViewBag.SubmitText = "Update";
    }
    else
    {
        ViewBag.Title = "New Sub Category";
        ViewBag.SubmitText = "Create";
    }
}

<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
                        <li class="breadcrumb-item active">@ViewBag.Title</li>
                    </ol>
                </div>
                <h4 class="page-title">@ViewBag.Title</h4>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <p class="sub-header">
                    Use this option to @ViewBag.SubmitText Sub Category.
                </p>

                @if (!string.IsNullOrEmpty(@ViewBag.Message))
                {
                    <div class="alert alert-success alert-dismissible bg-success text-white border-0 fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        @ViewBag.Message
                    </div>
                }

                @if (!ViewData.ModelState.IsValid && Model.BrokenBusinessRules?.Count > 0)
                {
                    <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        @Html.ValidationSummary(true)
                    </div>
                }

                <div class="row">
                    <div class="col-lg-2">
                    </div>
                    <div class="col-lg-8">
                        @using (Html.BeginForm())
                        {
                            <div class="form-group mb-3">
                                @Html.LabelFor(model => model.CategoryId)

                                @Html.DropDownListFor(model => model.CategoryId, new SelectList(Model.Categories, "Id", "ConfigValue"), htmlAttributes: new { @class = "form-control" })

                                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })

                            </div>


                            <div class="form-group mb-3">
                                @Html.LabelFor(model => model.SubCategoryName)
                                @Html.TextBoxFor(model => model.SubCategoryName, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.SubCategoryName, "", new { @class = "text-danger" })
                            </div>                           

                            <div class="form-group mb-0">
                                <input type="submit" class="btn btn-primary" value=@ViewBag.SubmitText>
                                <a href="@Url.Action("Index", "SubCategories")" class="btn btn-outline-blue waves-effect waves-light" id="demo-delete-row"><i class="mdi mdi-account-multiple mr-1"></i>Go to Sub Category List</a>
                            </div>
                        }
                    </div>
                    <div class="col-lg-2">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SmartPlanner/SmartPlanner/Views/SubCategories/Index.cshtml
@model IEnumerable<SmartPlanner.BusinessLayer.SubCategory>

@{
    ViewBag.Title = "Manage Sub Categories";
}

<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
                        <li class="breadcrumb-item active">Manage Sub Categories</li>
                    </ol>
                </div>
                <h4 class="page-title">Manage Sub Categories</h4>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <p class="sub-header">
                    Use this option to manage the Sub Categories.
                </p>

                <!-- Start Display the message as a dismissable alert -->
                @if (!string.IsNullOrEmpty(@ViewBag.Message))
                {
                    <div class="alert alert-success alert-dismissible bg-success text-white border-0 fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        @ViewBag.Message
                    </div>
                }
                <!-- End Display the message as a dismissable alert -->

                    <a href="@Url.Action("Detail", "SubCategories")" class="btn btn-primary btn-rounded waves-effect waves-light" id="demo-delete-row"><i class="mdi mdi-account-multiple-plus mr-1"></i>New Sub Category</a>

                <table id="demo-custom-toolbar" data-toggle="table"
                       data-toolbar="#demo-delete-row"
                       data-search="true"
                       data-show-refresh="true"
                       data-show-columns="true"
                       data-sort-name="name"
                       data-page-list="[5, 10, 20]"
                       data-page-size="10"
                       data-pagination="true" data-show-pagination-switch="true" class="table-bordered ">
                    <thead class="thead-light">
                        <tr>
                            <th data-field="name" data-sortable="true">@Html.DisplayNameFor(model => model.CategoryId) </th>
                            <th data-field="module" data-sortable="true">@Html.DisplayNameFor(model => model.SubCategoryName) </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.Category.ConfigValue) </td>
                                <td>@Html.DisplayFor(modelItem => item.SubCategoryName)</td>
                                <td>
                                    <a href="@Url.Action("Detail", "SubCategories", new { id = item.Id })" class="btn btn-info btn-sm"><i class="fa fa-edit"></i></a> |
                                    <a href="@Url.Action("Delete", "SubCategories", new { id = item.Id })" class="btn btn-danger btn-sm"><i class="fa fa-trash-alt"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div> <!-- end card-box-->
        </div> <!-- end col-->
    </div>
</div>