SmartPlanner/SmartPlanner/Controllers/SMVBankController.cs
using SmartPlanner.Attributes;
using SmartPlanner.BusinessLayer;
using SmartPlanner.BusinessLayer.DTOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static SmartPlanner.BusinessLayer.Common.Enums;

namespace SmartPlanner.Controllers
{
    [AuthenticateUserSession]
    public class SMVBankController : Controller
    {
        private StyleDetailService _styleDetailService = new StyleDetailService();
        private StyleProductService _styleProductService = new StyleProductService();

        private void SetConfigTablesValues(SMVBankDTO smvBank)
        {
            ConfigurationTableValueService configService = new ConfigurationTableValueService();

            smvBank.Buyers = new BuyerService().ListBuyers("Name", true);
            smvBank.Customers = new CustomerService().ListCustomers("Name", true);
            //smvBank.Categories = configService.ListByConfigId((int)EnumConfigurationTables.Category, true);
            //smvBank.SubCategories = new List<SubCategory>();
            smvBank.StyleDetails = _styleDetailService.GetList();
            smvBank.StyleProducts = new List<StyleProduct>();

        }

        // GET: SMVBank
        public ActionResult Index()
        {
            SMVBankDTO smvBank = new SMVBankDTO();

            this.SetConfigTablesValues(smvBank);

            return View(smvBank);
        }

        public ActionResult Inquiry()
        {
            List<StyleRevision> styleRevisions = new StyleRevisionService().GetList();
            return View(styleRevisions);
        }


        public ActionResult LoadStyleProducts(int styleProductId)
        {
            return PartialView("_StyleDetail", _styleProductService.GetEntityById(styleProductId));
        }

        public ActionResult GetStyleList(int? buyerId, int? customerId)
        {
            List<IdNameDTO> styles = _styleDetailService.ListForSMV(buyerId.Value, customerId.Value);
            return Json(styles, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetStyleDetailList(int? buyerId, int? customerId)
        {
            List<StyleDetail> styles = _styleDetailService.ListForBuyerCustomer(buyerId.Value, customerId.Value);
            return Json(styles, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CalculateChangeOver(int product1Id, int product2Id)
        {
            int changeOver = 0;

            StyleProduct product1 = _styleProductService.GetEntityById(product1Id);
            StyleProduct product2 = _styleProductService.GetEntityById(product2Id);


            if (product1.ProductId != product2.ProductId || product1.CategoryId != product2.CategoryId || product1.SubCategoryId != product2.SubCategoryId)
            {
                changeOver = 100;
            }
            else if (product1.FeatureList.Count.Equals(0) || product2.FeatureList.Count.Equals(0) || product1.OperationBreakdowns.Count.Equals(0) || product2.OperationBreakdowns.Count.Equals(0))
            {
                changeOver = 100;
            }
            else
            {
                int commonFeatures = product1.FeatureList.Intersect(product2.FeatureList).Count();

                int commonOperations = product1.OperationBreakdowns.Intersect(product2.OperationBreakdowns).Count();

                changeOver = ((commonFeatures * 50) / product2.FeatureList.Count) + ((commonOperations * 50) / product2.OperationBreakdowns.Count);

            }

            return Json(changeOver, JsonRequestBehavior.AllowGet);
        }
    }
}

SmartPlanner/SmartPlanner/Controllers/StyleDetailsController.cs
using SmartPlanner.Attributes;
using SmartPlanner.BusinessLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static SmartPlanner.BusinessLayer.Common.Enums;

namespace SmartPlanner.Controllers
{
    [AuthenticateUserSession]
    public class StyleDetailsController : Controller
    {
        private StyleDetailService _styleDetailService = new StyleDetailService();
        private SubCategoryService _subCategoryService = new SubCategoryService();
        private StyleProductService _styleProductService = new StyleProductService();

        private void SetConfigTablesValues(StyleDetail styleDetail, bool isEdit = false)
        {
            ConfigurationTableValueService configService = new ConfigurationTableValueService();
            styleDetail.AppearanceList = configService.ListByConfigId((int)EnumConfigurationTables.Appearance, true);
            
            styleDetail.FabricTypes = configService.ListByConfigId((int)EnumConfigurationTables.FabricType, true);
            styleDetail.Divisions = configService.ListByConfigId((int)EnumConfigurationTables.Division, true);
            styleDetail.Operations = configService.ListByConfigId((int)EnumConfigurationTables.Operation, true);
            styleDetail.TimeTables = configService.ListByConfigId((int)EnumConfigurationTables.TimeTable, true);
            
            styleDetail.Categories = configService.ListByConfigId((int)EnumConfigurationTables.Category, true);
            styleDetail.FeaturesList = configService.ListByConfigId((int)EnumConfigurationTables.FeatureList, true);
            styleDetail.Products = configService.ListByConfigId((int)EnumConfigurationTables.Product, true);

            styleDetail.Buyers = new BuyerService().ListBuyers("Name",true);
            styleDetail.Customers = new CustomerService().ListCustomers("Name", true);
            styleDetail.Merchants = new UserService().ListUsers("FullName", true);
            styleDetail.IndustrialEngineers = new UserService().ListUsers("FullName", true);
            styleDetail.SampleStatuses = new SampleApprovalStatusService().ListSampleApproval();


            if (isEdit)
            {
                //styleDetail.SubCategories = _subCategoryService.ListForCategoryId(styleDetail.CategoryId);
            }
            else
            {
                styleDetail.StyleProducts = new List<IdNameDTO>();

                //styleDetail.SubCategories = new List<SubCategory>();
                //styleDetail.AdditionalInformationFileNames = new List<AdditionalFileDTO>();
                //styleDetail.FeatureList = new List<string>();
            }

        }

        // GET: StyleDetails
        public ActionResult Index()
        {
            return View(_styleDetailService.GetList());
        }

        public ActionResult Detail(int? id, EnumSMVInquiryType isInquiry = EnumSMVInquiryType.None, int inquiryRevisionId = 0)
        {
            StyleDetail styleDetail = new StyleDetail();

            Session["StyleProducts"] = null;

            if (id.HasValue && id.Value > 0)
            {
                styleDetail = _styleDetailService.GetEntityById(id.Value);
                this.SetConfigTablesValues(styleDetail, true);
                ViewBag.IsInquiry = isInquiry;
            }
            else
            {
                ViewBag.IsInquiry = EnumSMVInquiryType.Request;
                this.SetConfigTablesValues(styleDetail);
            }

            ViewBag.InquiryRevisionId = inquiryRevisionId;
            return View(styleDetail);
        }

        [HttpPost]
        public ActionResult Detail(StyleDetail styleDetail, EnumSMVInquiryType isInquiry = EnumSMVInquiryType.None, int inquiryRevisionId = 0)
        {
            ViewBag.InquiryRevisionId = inquiryRevisionId;
            ViewBag.IsInquiry = isInquiry;

            try
            {
                this.SetConfigTablesValues(styleDetail,true);

                if (!ModelState.IsValid)
                    return View(styleDetail);

                bool isAdded = false;

                if (styleDetail.Id == 0)
                    isAdded = true;

                if (!_styleDetailService.Save(styleDetail, isInquiry, inquiryRevisionId) && !string.IsNullOrWhiteSpace(styleDetail.BrokenBusinessRulesText))
                {
                    ModelState.AddModelError("", styleDetail.BrokenBusinessRulesText);

                    return View(styleDetail);
                }

                if (isAdded)
                {
                    ModelState.Clear();
                    ViewBag.Message = "Style detail added successfully";

                    StyleDetail newStyle = new StyleDetail();
                    this.SetConfigTablesValues(newStyle,true);
                    return View(newStyle);
                }
                else
                {
                    ViewBag.Message = "Style detail updated successfully";
                    styleDetail = _styleDetailService.GetEntityById(styleDetail.Id);
                    this.SetConfigTablesValues(styleDetail,true);
                    return View(styleDetail);
                }
            }
            catch (Exception ex)
            {
                if (ex.Message.StartsWith("Violation of UNIQUE KEY constraint 'AK_StyleDetails_StyleNumber_Buyer'."))
                    ModelState.AddModelError("", "This style number already created for this buyer.");
                else
                    ModelState.AddModelError("", ex.Message);

                return View(styleDetail);
            }
        }

        [HttpPost]
        public JsonResult AddAdditionalFile()
        {

            int styleId = Convert.ToInt32(Request["Id"]);

            for (int i = 0; i < Request.Files.Count; i++)
            {
                HttpPostedFileBase file = Request.Files[i];
                //_styleDetailService.SaveAdditionalInformations(file, styleId);
            }


            var additionalFiles = new List<string>();// _styleDetailService.GetEntityById(styleId).AdditionalInformationFileNames.ToList();

            return Json(additionalFiles);
        }

        [HttpPost]
        public JsonResult AddFeature()
        {

            int styleId = Convert.ToInt32(Request["Id"]);
            string featureName = Convert.ToString(Request["FeatureName"]);

            //_styleDetailService.SaveFeaturesList(featureName, styleId);

            var featuresList = new List<string>();//= _styleDetailService.GetEntityById(styleId).FeatureList.ToList();

            return Json(featuresList);
        }

        public ActionResult Delete(int id)
        {
            return View(_styleDetailService.GetEntityById(id));
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                _styleDetailService.DeleteById(id);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                if (ex.Message.StartsWith("The DELETE statement conflicted with the REFERENCE constraint"))
                    ModelState.AddModelError("", "Unable to delete this style detail as involved with some actions");
                return View(_styleDetailService.GetEntityById(id));
            }
        }

        public ActionResult GetSubCategories(int? category)
        {
            if (!category.HasValue) return null;

            List<SubCategory> subCategories = _subCategoryService.ListForCategoryId(category.Value);
            return Json(subCategories, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult AddProducts()
        {
            List<StyleProduct> styleProducts = new List<StyleProduct>();

            if (Session.Keys.Count > 0 && Session["StyleProducts"] != null)
            {
                styleProducts = (List<StyleProduct>)Session["StyleProducts"];
            }

            int styleId = Convert.ToInt32(Request["StyleId"]);
            int productId = Convert.ToInt32(Request["ProductId"]);

            StyleProduct newStyleProduct = new StyleProduct();
            newStyleProduct.StyleId = styleId;
            newStyleProduct.ProductId = productId;

            _styleProductService.Save(newStyleProduct);

            styleProducts = _styleProductService.ListForStyleId(styleId);
            Session["StyleProducts"] = styleProducts;

            return Json(styleProducts);
        }
    }
}

SmartPlanner/SmartPlanner/Views/SMVBank/Inquiry.cshtml
@using SmartPlanner.BusinessLayer.Common
@model IEnumerable<SmartPlanner.BusinessLayer.StyleRevision>

@{
    ViewBag.Title = "Manage SMV Inquiries";
}

<!-- Start Content-->
<div class="container-fluid">
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
                        <li class="breadcrumb-item active">Manage Styles</li>
                    </ol>
                </div>
                <h4 class="page-title">Manage SMV Inquiries</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <p class="sub-header">
                    Use this option to manage the SMV inquiries of your organization.
                </p>

                <!-- Start Display the message as a dismissable alert -->
                @if (!string.IsNullOrEmpty(@ViewBag.Message))
                {
                    <div class="alert alert-success alert-dismissible bg-success text-white border-0 fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        @ViewBag.Message
                    </div>
                }
                <!-- End Display the message as a dismissable alert -->

                @if (Helper.GetAccessType(Enums.EnumAccessModules.SMVManagement).Equals(Enums.UserAccessType.ReadWrite))
                {
                    <a href="@Url.Action("Detail", "StyleDetails")" class="btn btn-primary btn-rounded waves-effect waves-light" id="demo-delete-row"><i class="mdi mdi-crop mr-1"></i>New SMV Inquiry</a>
                }

                <table id="demo-custom-toolbar" data-toggle="table"
                       data-toolbar="#demo-delete-row"
                       data-search="true"
                       data-show-refresh="true"
                       data-show-columns="true"
                       data-sort-name="requestedby"
                       data-page-list="[5, 10, 20]"
                       data-page-size="10"
                       data-pagination="true" data-show-pagination-switch="true" class="table-bordered ">

                    <thead class="thead-light">
                        <tr>
                            <th data-field="requestedby" data-sortable="true">@Html.DisplayNameFor(model => model.RequestedById)</th>
                            <th data-field="inquirytype" data-sortable="true">@Html.DisplayNameFor(model => model.InquiryType)</th>
                            <th data-field="buyer" data-sortable="true">@Html.DisplayNameFor(model => model.StyleDetail.BuyerId)</th>
                            <th data-field="department" data-sortable="true">@Html.DisplayNameFor(model => model.StyleDetail.Department)</th>
                            <th data-field="stylenumber" data-sortable="true">@Html.DisplayNameFor(model => model.StyleDetail.StyleNumber)</th>
                            <th data-field="requesteddate" data-sortable="true">@Html.DisplayNameFor(model => model.RequestedDateText)</th>
                            <th data-field="accepteddate" data-sortable="true">@Html.DisplayNameFor(model => model.RevisedDateText)</th>
                            <th data-field="acceptedby" data-sortable="true">@Html.DisplayNameFor(model => model.AcceptedById)</th>

                            @if (Helper.GetAccessType(Enums.EnumAccessModules.StyleManagementIE).Equals(Enums.UserAccessType.ReadWrite) || Helper.GetAccessType(Enums.EnumAccessModules.SMVManagement).Equals(Enums.UserAccessType.ReadWrite))
                            {
                                <th></th>
                            }
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.RequestedBy.FullName)</td>
                                <td>@Html.DisplayFor(modelItem => item.InquiryType)</td>
                                <td>@Html.DisplayFor(modelItem => item.StyleDetail.Buyer.Name)</td>
                                <td>@Html.DisplayFor(modelItem => item.StyleDetail.Department)</td>
                                <td>@Html.DisplayFor(modelItem => item.StyleDetail.StyleNumber)</td>
                                <td>@Html.DisplayFor(modelItem => item.RequestedDateText)</td>
                                <td>@Html.DisplayFor(modelItem => item.RevisedDateText)</td>
                                <td>@Html.DisplayFor(modelItem => item.AcceptedBy.FullName)</td>

                                @if (Helper.GetAccessType(Enums.EnumAccessModules.StyleManagementIE).Equals(Enums.UserAccessType.ReadWrite) || Helper.GetAccessType(Enums.EnumAccessModules.SMVManagement).Equals(Enums.UserAccessType.ReadWrite))
                                {
                                    <td>
                                        <a href="@Url.Action("Detail", "StyleDetails", new { id = item.StyleId, isInquiry=3, inquiryRevisionId = item.Id })" class="btn btn-info btn-sm"><i class="fa fa-edit"></i></a>
                                    </td>
                                }
                            </tr>
                        }
                    </tbody>
                </table>
            </div> <!-- end card-box-->
        </div> <!-- end col-->
    </div>
    <!-- end row -->
</div>