SmartPlanner/SmartPlanner/Controllers/OrderDetailsController.cs
using SmartPlanner.Attributes;
using SmartPlanner.BusinessLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static SmartPlanner.BusinessLayer.Common.Enums;
using SmartPlanner.BusinessLayer.Common;
using System.Text;
using Newtonsoft.Json.Linq;
using Extensions = SmartPlanner.BusinessLayer.Common.Extensions;
using System.Data;
using System.IO;
using SmartPlanner.BusinessLayer.Excel;

namespace SmartPlanner.Controllers
{
    [AuthenticateUserSession]
    public class OrderDetailsController : Controller
    {
        private OrderDetailService _orderDetailService = new OrderDetailService();
        private TnACalendarService _tnACalendarService = new TnACalendarService();
        private OrderCombinationService _orderCombinationService = new OrderCombinationService();
        // GET: OrderDetails

        private void SetConfigTablesValues(OrderDetail orderDetail)
        {
            ConfigurationTableValueService configService = new ConfigurationTableValueService();
            orderDetail.PlanningSeasons = configService.ListByConfigId((int)EnumConfigurationTables.PlanningSeason, true);
            orderDetail.DestinationMedias = configService.ListByConfigId((int)EnumConfigurationTables.DestinationMedia, true);
            orderDetail.Destinations = configService.ListByConfigId((int)EnumConfigurationTables.Destination, true);
            orderDetail.BuyGroups = configService.ListByConfigId((int)EnumConfigurationTables.BuyGroup, true);

            orderDetail.Vendors = configService.ListByConfigId((int)EnumConfigurationTables.Vendor, true);
            orderDetail.Divisions = configService.ListByConfigId((int)EnumConfigurationTables.Division, true);
            orderDetail.Products = configService.ListByConfigId((int)EnumConfigurationTables.Product, true);
            orderDetail.DistributeFromList = configService.ListByConfigId((int)EnumConfigurationTables.DistributeFrom, true);
            orderDetail.DeliverToList = configService.ListByConfigId((int)EnumConfigurationTables.DeliverTo, true);

            orderDetail.Methods = configService.ListByConfigId((int)EnumConfigurationTables.Method, true);
            orderDetail.FactoryNames = new FactoryService().GetList();
            orderDetail.POTypes = configService.ListByConfigId((int)EnumConfigurationTables.POType, true);
            orderDetail.TimeTables = configService.ListByConfigId((int)EnumConfigurationTables.TimeTable, true);

            orderDetail.Customers = new CustomerService().ListCustomers("Name",true);
            orderDetail.Buyers = new BuyerService().ListBuyers("Name",true);

            orderDetail.EmblishmentPlants = configService.ListByConfigId((int)EnumConfigurationTables.EmblishmentPlant, true);
            orderDetail.Users = new UserService().ListUsers("UserName", true);
            orderDetail.Styles = new StyleDetailService().GetList();

            orderDetail.WashingPlants = configService.ListByConfigId((int)EnumConfigurationTables.WashingPlant, true);
            orderDetail.PrintingPlants = configService.ListByConfigId((int)EnumConfigurationTables.PrintingPlant, true);
            orderDetail.Sizes = configService.ListByConfigId((int)EnumConfigurationTables.Size, true);
            orderDetail.PriceTypes = configService.ListByConfigId((int)EnumConfigurationTables.PriceType, true);
            orderDetail.SewingPlants = configService.ListByConfigId((int)EnumConfigurationTables.SewingPlant, true);
            orderDetail.SampleStatuses = configService.ListByConfigId((int)EnumConfigurationTables.SampleStatus, true);
            orderDetail.OrderInquiryStatuses = new OrderInquiryStatusService().GetList();
            orderDetail.Merchants = new UserService().ListUsers("FullName", true);
            orderDetail.Planners = new UserService().ListUsers("FullName", true);

            orderDetail.Colors = configService.ListByConfigId((int)EnumConfigurationTables.Colors, true);
            orderDetail.CustomerSizes = new List<string>();
            orderDetail.CustomerColors = new List<string>();

        }

        public ActionResult Index()
        {
            return View(_orderDetailService.ListOrders());
        }

        public ActionResult TnaIndex(int type)
        {
            ViewBag.Type = type;
            return View(_orderDetailService.ListForType(type));
        }

        public ActionResult CutIndex()
        {
            return View(_orderDetailService.ListOrders());
        }

        [AuthAccess(EnumAccessModules.OrderManagement)]
        public ActionResult Detail(int? id)
        {
            OrderDetail orderDetail = new OrderDetail();
            //Session["OrderSizeColorCombinations"] = null;

            if (id.HasValue && id.Value > 0)
            {
                orderDetail = _orderDetailService.GetEntityById(id.Value);
            }

            this.SetConfigTablesValues(orderDetail);

            return View(orderDetail);
        }

        [AuthAccess(EnumAccessModules.OrderManagement)]
        public ActionResult ViewDetail(int? id)
        {
            OrderDetail orderDetail = new OrderDetail();

            if (id.HasValue && id.Value > 0)
            {
                orderDetail = _orderDetailService.GetEntityById(id.Value);
            }

            this.SetConfigTablesValues(orderDetail);

            return View(orderDetail);
        }

        [AuthAccess(EnumAccessModules.TnAManagement)]
        public ActionResult TnaDetail(int? id, int? productId, int isTna = 1)
        {
            OrderDetail orderDetail = new OrderDetail();

            if (id.HasValue && id.Value > 0 && productId.HasValue && productId.Value > 0)
                orderDetail = _orderDetailService.GetEntityById(id.Value);

            orderDetail.ProductId = productId.Value;
            orderDetail.TnACalendar = _tnACalendarService.GetCalendarsForOrder(orderDetail.Id, orderDetail.ProductId);

            this.SetConfigTablesValues(orderDetail);

            ViewBag.IsTna = isTna;

            return View(orderDetail);
        }

        [AuthAccess(EnumAccessModules.TnAManagement)]
        public ActionResult ViewTnaDetail(int? id, int? productId, int isTna = 1)
        {
            OrderDetail orderDetail = new OrderDetail();

            if (id.HasValue && id.Value > 0 && productId.HasValue && productId.Value > 0)
                orderDetail = _orderDetailService.GetEntityById(id.Value);

            orderDetail.ProductId = productId.Value;
            orderDetail.TnACalendar = _tnACalendarService.GetCalendarsForOrder(orderDetail.Id, orderDetail.ProductId);

            this.SetConfigTablesValues(orderDetail);

            ViewBag.IsTna = isTna;

            return View(orderDetail);
        }

        [AuthAccess(EnumAccessModules.OrderManagementCut)]
        public ActionResult CutDetail(int? id)
        {
            OrderDetail orderDetail = new OrderDetail();
            //Session["OrderSizeColorCombinations"] = null;

            if (id.HasValue && id.Value > 0)
            {
                orderDetail = _orderDetailService.GetEntityById(id.Value);

                //if(!(orderDetail.OrderCombinations.Count.Equals(1) && orderDetail.OrderCombinations[0].ColorId.Equals(0)))
                //    Session["OrderSizeColorCombinations"] = orderDetail.OrderCombinations;
            }

            //orderDetail.TnACalendar = _tnACalendarService.GetCalendarsForOrder(orderDetail.Id);
            this.SetConfigTablesValues(orderDetail);

            return View(orderDetail);
        }

        [AuthAccess(EnumAccessModules.OrderManagementCut)]
        public ActionResult ViewCutDetail(int? id)
        {
            OrderDetail orderDetail = new OrderDetail();

            if (id.HasValue && id.Value > 0)
            {
                orderDetail = _orderDetailService.GetEntityById(id.Value);
            }

            this.SetConfigTablesValues(orderDetail);

            return View(orderDetail);
        }

        [AuthAccess(EnumAccessModules.TnAManagement)]
        public ActionResult StyleProducts(int? id, int isTna = 0)
        {
            if (!id.HasValue || id.Value < 1) return View();

            OrderDetail orderDetail = _orderDetailService.GetEntityById(id.Value);

            List<StyleProduct> styleProducts = new StyleProductService().ListForStyleId(orderDetail.StyleId);
            ViewBag.OrderId = id.Value;

            ViewBag.IsTna = isTna;

            return View(styleProducts);
        }

        [HttpPost]
        public ActionResult Detail(OrderDetail orderDetail)
        {
            try
            {
                this.SetConfigTablesValues(orderDetail);

                if (!ModelState.IsValid)
                {
                   //orderDetail.TnACalendar = _tnACalendarService.GetCalendarsForOrder(orderDetail.Id, orderDetail.ProductId);
                    return View(orderDetail);
                }

                bool isAdded = false;

                if (orderDetail.Id == 0)
                    isAdded = true;

                //if (Session["OrderSizeColorCombinations"] != null)
                //{
                //    orderDetail.OrderCombinations = (List<OrderCombination>)Session["OrderSizeColorCombinations"];
                //}

                orderDetail.OrderInquiryStatusId = 1;

                if (!_orderDetailService.Save(orderDetail) && !string.IsNullOrWhiteSpace(orderDetail.BrokenBusinessRulesText))
                {
                    //orderDetail.TnACalendar = _tnACalendarService.GetCalendarsForOrder(orderDetail.Id);
                    ModelState.AddModelError("", orderDetail.BrokenBusinessRulesText);
                    return View(orderDetail);
                }
                //orderDetail.TnACalendar = _tnACalendarService.GetCalendarsForOrder(orderDetail.Id);

                if (isAdded)
                {
                    ModelState.Clear();

SmartPlanner/SmartPlanner/Views/OrderDetails/Combination.cshtml
@using SmartPlanner.BusinessLayer.Common
@model SmartPlanner.BusinessLayer.OrderCombination

@{
    if (Model == null || Model.Id > 0)
    {
        ViewBag.Title = "Update Order Combination";
        ViewBag.SubmitText = "Update";
    }
    else
    {
        ViewBag.Title = "Create Order Combination";
        ViewBag.SubmitText = "Create";
    }

    ViewBag.IsOrder = "form-control  disabled";
    ViewBag.IsCut = "form-control  disabled";

    if (Helper.GetAccessType(Enums.EnumAccessModules.OrderManagementCut).Equals(Enums.UserAccessType.ReadWrite))
    {
        ViewBag.IsCut = "form-control";
    }

    if (Helper.GetAccessType(Enums.EnumAccessModules.OrderManagement).Equals(Enums.UserAccessType.ReadWrite))
    {
        ViewBag.IsOrder = "form-control";
    }
}

<!-- Start Content-->
<div class="container-fluid">
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
                        <li class="breadcrumb-item active">@ViewBag.Title</li>
                    </ol>
                </div>
                <h4 class="page-title">@ViewBag.Title</h4>
            </div>
        </div>
    </div>

    <!-- end page title -->

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <p class="sub-header">
                    Use this option to @ViewBag.SubmitText the product, size, and color combination for order details.
                </p>
                <!-- Start Display the message as a dismissable alert -->
                @if (!string.IsNullOrEmpty(@ViewBag.Message))
                {
                    <div class="alert alert-success alert-dismissible bg-success text-white border-0 fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        @ViewBag.Message
                    </div>
                }

                @if (!ViewData.ModelState.IsValid)
                {
                    <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    </div>
                }
                <!-- End Display the message as a dismissable alert -->

                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-8">
                        @using (Html.BeginForm("Combination", "OrderDetails", FormMethod.Post, htmlAttributes: new { @class = "needs-validation" }))
                        {
                            @Html.HiddenFor(model => model.Id)
                            @Html.HiddenFor(model => model.OrderDetailsId)
                            @Html.HiddenFor(model => model.StyleProductId)
                            @Html.HiddenFor(model => model.Wastage)

                            <div class="form-row">

                                <div class="form-group  col-md-12">
                                    @Html.LabelFor(model => model.StyleProductId)
                                    @Html.TextBoxFor(model => model.StyleProduct.ProductName, htmlAttributes: new { @class = "form-control disabled" })
                                    @Html.ValidationMessageFor(model => model.StyleProductId, "", new { @class = "text-danger" })
                                </div>

                                <div class="form-group  col-md-12">
                                    @Html.LabelFor(model => model.ColorName)
                                    @Html.TextBoxFor(model => model.ColorName, htmlAttributes: new { @class = "form-control disabled" })
                                    @Html.ValidationMessageFor(model => model.ColorName, "", new { @class = "text-danger" })
                                </div>

                                <div class="form-group  col-md-12">
                                    @Html.LabelFor(model => model.SizeName)
                                    @Html.TextBoxFor(model => model.SizeName, htmlAttributes: new { @class = "form-control disabled" })
                                    @Html.ValidationMessageFor(model => model.SizeName, "", new { @class = "text-danger" })
                                </div>

                                <div class="form-group  col-md-12">
                                    @Html.LabelFor(model => model.Qty)
                                    @Html.TextBoxFor(model => model.Qty, new { @class = @ViewBag.IsOrder, type = "text", data_toggle = "touchspin",
                                   data_bts_max = "9999999999",
                                   onkeypress = "return IsNumber(event)", ondrop = "return false;", onpaste = "return false;" })
                                    @Html.ValidationMessageFor(model => model.Qty, "", new { @class = "text-danger" })
                                </div>

                                <div class="form-group  col-md-12">
                                    @Html.LabelFor(model => model.PlanDeliveryQty)
                                    @Html.TextBoxFor(model => model.PlanDeliveryQty, new { @class = "form-control disabled" })
                                    @Html.ValidationMessageFor(model => model.PlanDeliveryQty, "", new { @class = "text-danger" })

                                </div>

                                <div class="form-group  col-md-12">
                                    @Html.LabelFor(model => model.CutQty)
                                    @Html.TextBoxFor(model => model.CutQty, new { @class = @ViewBag.IsCut, type = "text", data_toggle = "touchspin",
                                   data_bts_max = "9999999999",
                                   onkeypress = "return IsNumber(event)", ondrop = "return false;", onpaste = "return false;" })
                                    @Html.ValidationMessageFor(model => model.CutQty, "", new { @class = "text-danger" })
                                </div>

                                <div class="form-group  col-md-12">
                                    @Html.LabelFor(model => model.ShipQty)
                                    @Html.TextBoxFor(model => model.ShipQty, new { @class = @ViewBag.IsCut, type = "text", data_toggle = "touchspin",
                                   data_bts_max = "9999999999",
                                   onkeypress = "return IsNumber(event)", ondrop = "return false;", onpaste = "return false;" })
                                    @Html.ValidationMessageFor(model => model.ShipQty, "", new { @class = "text-danger" })
                                </div>

                            </div>

                            <div class="form-group mb-0">
                                <input type="submit" class="btn btn-primary" value=@ViewBag.SubmitText>
                                <a href="@Url.Action("Detail", "OrderDetails", new { id=Model.OrderDetailsId})" class="btn btn-outline-blue waves-effect waves-light" id="demo-delete-row"><i class="mdi mdi-cart-outline mr-1"></i>Go to Order</a>
                            </div>


                        }
                    </div>
                    <div class="col-lg-2"></div>
                </div>

            </div> <!-- end card-box-->
        </div> <!-- end col-->
    </div>
    <!-- end row -->
</div>

@section scripts{

    <script type="text/javascript">
        $("#Qty").change(function () {
            var wasteQty = $("#Qty").val() * $("#Wastage").val() / 100;
            var planQty = Number($("#Qty").val()) + Number(Math.floor(wasteQty));
            $("#PlanDeliveryQty").val(planQty);

        });
    </script>

}

SmartPlanner/SmartPlanner/Views/OrderDetails/CutIndex.cshtml
@using SmartPlanner.BusinessLayer.Common
@model IEnumerable<SmartPlanner.BusinessLayer.OrderDetail>

@{
    ViewBag.Title = "Manage Cutting Output";
}

<!-- Start Content-->
<div class="container-fluid">
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
                        <li class="breadcrumb-item active">Manage Cutting Output</li>
                    </ol>
                </div>
                <h4 class="page-title">Manage Cutting Output</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">

                <p class="sub-header">
                    Use this option to manage Cutting Output of the orders of your organization.
                </p>

                <!-- Start Display the message as a dismissable alert -->
                @if (!string.IsNullOrEmpty(@ViewBag.Message))
                {
                    <div class="alert alert-success alert-dismissible bg-success text-white border-0 fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        @ViewBag.Message
                    </div>
                }
                <!-- End Display the message as a dismissable alert -->
                <table id="demo-custom-toolbar" data-toggle="table"
                       data-toolbar="#demo-delete-row"
                       data-search="true"
                       data-show-refresh="true"
                       data-show-columns="true"
                       data-sort-name="salesordernumber"
                       data-page-list="[5, 10, 20]"
                       data-page-size="10"
                       data-pagination="true" data-show-pagination-switch="true" class="table-bordered ">

                    <thead class="thead-light">
                        <tr>
                            <th data-field="factory" data-sortable="true">@Html.DisplayNameFor(model => model.FactoryNameId)</th>
                            <th data-field="buyer" data-sortable="true">@Html.DisplayNameFor(model => model.BuyerId)</th>
                            <th data-field="customer" data-sortable="true">@Html.DisplayNameFor(model => model.CustomerId)</th>
                            <th data-field="style" data-sortable="true">@Html.DisplayNameFor(model => model.StyleId)</th>
                            <th data-field="customerponumber" data-sortable="true">PO No.</th>
                            <th data-field="salesordernumber" data-sortable="true">Order Ref.</th>
                            <th data-field="orderqty" data-sortable="true">Order Qty</th>
                            <th data-field="repeat" data-sortable="true">Repeat</th>
                            <th data-field="shipmentdate" data-sortable="true">@Html.DisplayNameFor(model => model.ShipmentDateText)</th>
                            <th data-field="price" data-sortable="true">@Html.DisplayNameFor(model => model.CM)</th>
                            <th data-field="currentkeyprocess" data-sortable="true">Curr. Process</th>
                            <th data-field="posibilitytodeliver" data-sortable="true">Posible</th>
                            <th data-field="merchant" data-sortable="true">@Html.DisplayNameFor(model => model.MerchantId)</th>

                            @if (!Helper.GetAccessType(Enums.EnumAccessModules.OrderManagementCut).Equals(Enums.UserAccessType.NoAccess))
                            {
                                <th></th>
                            }
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.FactoryName.FactoryName)</td>
                            <td>@Html.DisplayFor(modelItem => item.Buyer.Name)</td>
                            <td>@Html.DisplayFor(modelItem => item.Customer.Name)</td>
                            <td>@Html.DisplayFor(modelItem => item.Style.StyleNumber)</td>
                            <td>@Html.DisplayFor(modelItem => item.CustomerPONumber)</td>
                            <td>@Html.DisplayFor(modelItem => item.SalesOrderNumber)</td>
                            <td>@Html.DisplayFor(modelItem => item.OrderQty)</td>
                            <td>@Html.DisplayFor(modelItem => item.Repeat)</td>
                            <td>@Html.DisplayFor(modelItem => item.ShipmentDateText)</td>
                            <td>@Html.DisplayFor(modelItem => item.CM)</td>
                            <td>@Html.DisplayFor(modelItem => item.CurrentKeyProcess)</td>
                            <td>@Html.DisplayFor(modelItem => item.PossibilityToDeliverString)</td>
                            <td>@Html.DisplayFor(modelItem => item.Merchant.FullName)</td>

                            @if (Helper.GetAccessType(Enums.EnumAccessModules.OrderManagementCut).Equals(Enums.UserAccessType.ReadWrite))
                            {
                                <td>
                                    <a href="@Url.Action("CutDetail", "OrderDetails", new { id = item.Id})" class="btn btn-info btn-sm"><i class="fa fa-edit"></i></a>
                                </td>
                            }
                            @if (Helper.GetAccessType(Enums.EnumAccessModules.OrderManagementCut).Equals(Enums.UserAccessType.ReadOnly))
                            {
                                <td>
                                    <a href="@Url.Action("ViewCutDetail", "OrderDetails", new { id = item.Id})" class="btn btn-warning btn-sm"><i class="fa fa-eye"></i></a>
                                </td>
                            }
                        </tr>
                        }
                    </tbody>
                </table>
            </div> <!-- end card-box-->
        </div> <!-- end col-->
    </div>
    <!-- end row -->
</div>

SmartPlanner/SmartPlanner/Views/OrderDetails/Delete.cshtml
@model SmartPlanner.BusinessLayer.OrderDetail

@{
    ViewBag.Title = "Delete Order Details";
}

<!-- Start Content-->
<div class="container-fluid">
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
                        <li class="breadcrumb-item active">@ViewBag.Title</li>
                    </ol>
                </div>
                <h4 class="page-title">@ViewBag.Title</h4>
            </div>
        </div>
    </div>

    <!-- end page title -->

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <h4 class="header-title">Are you sure you want to delete this?</h4>

                <!-- Start Display the message as a dismissable alert -->
                @if (!string.IsNullOrEmpty(@ViewBag.Message))
                {
                    <div class="alert alert-success alert-dismissible bg-success text-white border-0 fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        @ViewBag.Message
                    </div>
                }

                @if (!ViewData.ModelState.IsValid)
                {
                    <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        @Html.ValidationSummary(true)
                    </div>
                }

                <!-- End Display the message as a dismissable alert -->

                <div class="row">
                    <div class="col-lg-2">
                    </div>
                    <div class="col-lg-8">
                        @using (Html.BeginForm("Delete", "OrderDetails", FormMethod.Post, htmlAttributes: new { @class = "needs-validation" }))
                        {

                            @Html.HiddenFor(model => model.Id)

                            <div class="form-group mb-3">

                                <dl class="row">
                                    <dt class="col-sm-3">
                                        @Html.DisplayNameFor(model => model.SalesOrderNumber)
                                    </dt>

                                    <dd class="col-sm-9">
                                        @Html.DisplayFor(model => model.SalesOrderNumber)
                                    </dd>

                                    <dt class="col-sm-3">
                                        @Html.DisplayNameFor(model => model.BuyerId)
                                    </dt>

                                    <dd class="col-sm-9">
                                        @Html.DisplayFor(model => model.Buyer.Name)
                                    </dd>

                                    <dt class="col-sm-3">
                                        @Html.DisplayNameFor(model => model.CustomerId)
                                    </dt>

                                    <dd class="col-sm-9">
                                        @Html.DisplayFor(model => model.Customer.Name)
                                    </dd>

                                    <dt class="col-sm-3">
                                        @Html.DisplayNameFor(model => model.StyleId)
                                    </dt>

                                    <dd class="col-sm-9">
                                        @Html.DisplayFor(model => model.Style.StyleNumber)
                                    </dd>
                                </dl>

                            </div>

                            <div class="form-group mb-0">
                                <input type="submit" class="btn btn-primary" value="Delete">

                                <a href="@Url.Action("Index", "OrderDetails")" class="btn btn-outline-blue waves-effect waves-light" id="demo-delete-row"><i class="mdi mdi-account-multiple mr-1"></i>Go to Order Details List</a>

                            </div>
                        }

                    </div>

                    <div class="col-lg-2">
                    </div>
                </div>

            </div> <!-- end card-box-->
        </div> <!-- end col-->
    </div>
    <!-- end row -->
</div>