SmartPlanner/SmartPlanner/Controllers/BuyersController.cs
using SmartPlanner.Attributes;
using SmartPlanner.BusinessLayer;
using SmartPlanner.BusinessLayer.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static SmartPlanner.BusinessLayer.Common.Enums;

namespace SmartPlanner.Controllers
{
    [AuthenticateUserSession]
    public class BuyersController : Controller
    {
        // GET: Buyers

        private BuyerService _buyerService = new BuyerService();

        public ActionResult Index()
        {
            return View(_buyerService.ListBuyers("Name", false));
        }

        public ActionResult Detail(int? id)
        {
            Buyer buyer = new Buyer();

            if (id.HasValue && id.Value > 0)
                buyer = _buyerService.GetEntityById(id.Value);

            return View(buyer);
        }

        [HttpPost]
        public ActionResult Detail(Buyer buyer)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(buyer);

                bool isAdded = false;

                if (buyer.Id == 0)
                    isAdded = true;

                if (!_buyerService.Save(buyer) && !string.IsNullOrWhiteSpace(buyer.BrokenBusinessRulesText))
                {
                    ModelState.AddModelError("", buyer.BrokenBusinessRulesText);
                    return View(buyer);
                }

                if (isAdded)
                {
                    ModelState.Clear();
                    ViewBag.Message = "Buyer added successfully";

                    Buyer newBuyer = new Buyer();
                    
                    return View(newBuyer);
                }
                else
                {
                    ViewBag.Message = "Buyer updated successfully";
                    return View(buyer);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(buyer);
            }
        }

        public ActionResult Delete(int id)
        {
            return View(_buyerService.GetEntityById(id));
        }

        // POST: Users/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                _buyerService.DeleteById(id);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                if (ex.Message.StartsWith("The DELETE statement conflicted with the REFERENCE constraint"))
                    ModelState.AddModelError("", "Unable to delete this buyer as involved with some actions");
                return View(_buyerService.GetEntityById(id));
            }
        }


    }
}

SmartPlanner/SmartPlanner/Views/Buyers/Delete.cshtml
@model SmartPlanner.BusinessLayer.Buyer

@{
    ViewBag.Title = "Delete Buyer";
}

<div class="container-fluid">

    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
                        <li class="breadcrumb-item active">@ViewBag.Title</li>
                    </ol>
                </div>
                <h4 class="page-title">@ViewBag.Title</h4>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <h4 class="header-title">Are you sure you want to delete this buyer?</h4>
                <!-- Start Display the message as a dismissable alert -->
                @if (!string.IsNullOrEmpty(@ViewBag.Message))
                {
                    <div class="alert alert-success alert-dismissible bg-success text-white border-0 fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        @ViewBag.Message
                    </div>
                }

                @if (!ViewData.ModelState.IsValid)
                {
                    <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        @Html.ValidationSummary(true)
                    </div>
                }

                <div class="row">
                    <div class="col-lg-2">
                    </div>
                    <div class="col-lg-8">
                        @using (Html.BeginForm())
                        {
                            <div class="form-group mb-3">
                                <dl class="row">

                                    <dt class="col-sm-3">
                                        @Html.DisplayNameFor(model => model.Name)
                                    </dt>

                                    <dd class="col-sm-9">
                                        @Html.DisplayFor(model => model.Name)
                                    </dd>

                                    <dt class="col-sm-3">
                                        @Html.DisplayNameFor(model => model.Country)
                                    </dt>

                                    <dd class="col-sm-9">
                                        @Html.DisplayFor(model => model.Country)
                                    </dd>

                                    <dt class="col-sm-3">
                                        @Html.DisplayNameFor(model => model.Address)
                                    </dt>

                                    <dd class="col-sm-9">
                                        @Html.DisplayFor(model => model.Address)
                                    </dd>

                                    <dt class="col-sm-3">
                                        @Html.DisplayNameFor(model => model.Mobile)
                                    </dt>

                                    <dd class="col-sm-9">
                                        @Html.DisplayFor(model => model.Mobile)
                                    </dd>

                                    <dt class="col-sm-3">
                                        @Html.DisplayNameFor(model => model.Email)
                                    </dt>

                                    <dd class="col-sm-9">
                                        @Html.DisplayFor(model => model.Email)
                                    </dd>

                                </dl>
                            </div>
                            <div class="form-group mb-0">
                                <input type="submit" class="btn btn-primary" value="Delete">
                                <a href="@Url.Action("Index", "Buyers")" class="btn btn-outline-blue waves-effect waves-light" id="demo-delete-row"><i class="mdi mdi-account-multiple mr-1"></i>Go To Buyers List</a>
                            </div>
                        }
                    </div>
                    <div class="col-lg-2">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SmartPlanner/SmartPlanner/Views/Buyers/Detail.cshtml
@model SmartPlanner.BusinessLayer.Buyer

@{
    if (Model == null || Model.Id > 0)
    {
        ViewBag.Title = "Update Buyer";
        ViewBag.SubmitText = "Update";
    }
    else
    {
        ViewBag.Title = "New Buyer";
        ViewBag.SubmitText = "Create";
    }
}

<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
                        <li class="breadcrumb-item active">@ViewBag.Title</li>
                    </ol>
                </div>
                <h4 class="page-title">@ViewBag.Title</h4>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <p class="sub-header">
                    Use this option to @ViewBag.SubmitText Buyer.
                </p>

                @if (!string.IsNullOrEmpty(@ViewBag.Message))
                {
                    <div class="alert alert-success alert-dismissible bg-success text-white border-0 fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        @ViewBag.Message
                    </div>
                }

                @if (!ViewData.ModelState.IsValid && Model.BrokenBusinessRules?.Count > 0)
                {
                    <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        @Html.ValidationSummary(true)
                    </div>
                }

                <div class="row">
                    <div class="col-lg-3">
                    </div>
                    <div class="col-lg-6">
                        @using (Html.BeginForm())
                        {
                            <div class="form-group mb-3">
                                @Html.LabelFor(model => model.Name)
                                @Html.TextBoxFor(model => model.Name, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group mb-3">
                                @Html.LabelFor(model => model.Country)
                                @Html.TextBoxFor(model => model.Country, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group mb-3">
                                @Html.LabelFor(model => model.Address)
                                @Html.TextBoxFor(model => model.Address, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group mb-3">
                                @Html.LabelFor(model => model.Mobile)
                                @Html.TextBoxFor(model => model.Mobile, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group mb-3">
                                @Html.LabelFor(model => model.Email)
                                @Html.TextBoxFor(model => model.Email, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>

                            <div class="border border-light p-2 mb-3">
                                <h5>Planning board color management</h5>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.PlannedColor)
                                    <div id="component-colorpicker" class="input-group" title="Using format option">
                                        @Html.TextBoxFor(model => model.PlannedColor, htmlAttributes: new { @class = "form-control input-lg" })
                                        <span class="input-group-append">
                                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                                        </span>
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.ActualColor)
                                    <div id="component-colorpickeractual" class="input-group" title="Using format option">
                                        @Html.TextBoxFor(model => model.ActualColor, htmlAttributes: new { @class = "form-control input-lg" })
                                        <span class="input-group-append">
                                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                                        </span>
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    @Html.LabelFor(model => model.ChangedColor)
                                    <div id="component-colorpickerchanged" class="input-group" title="Using format option">
                                        @Html.TextBoxFor(model => model.ChangedColor, htmlAttributes: new { @class = "form-control input-lg" })
                                        <span class="input-group-append">
                                            <span class="input-group-text colorpicker-input-addon"><i></i></span>
                                        </span>
                                    </div>
                                </div>

                            </div>

                            

                            <div class="form-group mb-0">
                                <input type="submit" class="btn btn-primary" value=@ViewBag.SubmitText>
                                <a href="@Url.Action("Index", "Buyers")" class="btn btn-outline-blue waves-effect waves-light" id="demo-delete-row"><i class="mdi mdi-account-multiple mr-1"></i>Go to Buyers List</a>
                            </div>
                        }
                    </div>
                    <div class="col-lg-3">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SmartPlanner/SmartPlanner/Views/Buyers/Index.cshtml
@model IEnumerable<SmartPlanner.BusinessLayer.Buyer>

@{
    ViewBag.Title = "Manage Buyers";
}

<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
                        <li class="breadcrumb-item active">Manage Buyers</li>
                    </ol>
                </div>
                <h4 class="page-title">Manage Buyers</h4>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <p class="sub-header">
                    Use this option to manage the buyer details.
                </p>

                <!-- Start Display the message as a dismissable alert -->
                @if (!string.IsNullOrEmpty(@ViewBag.Message))
                {
                    <div class="alert alert-success alert-dismissible bg-success text-white border-0 fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        @ViewBag.Message
                    </div>
                }
                <!-- End Display the message as a dismissable alert -->

                <a href="@Url.Action("Detail", "Buyers")" class="btn btn-primary btn-rounded waves-effect waves-light" id="demo-delete-row"><i class="mdi mdi-account-multiple-plus mr-1"></i>New Buyer</a>

                <table id="demo-custom-toolbar" data-toggle="table"
                       data-toolbar="#demo-delete-row"
                       data-search="true"
                       data-show-refresh="true"
                       data-show-columns="true"
                       data-sort-name="name"
                       data-page-list="[5, 10, 20]"
                       data-page-size="10"
                       data-pagination="true" data-show-pagination-switch="true" class="table-bordered ">
                    <thead class="thead-light">
                        <tr>
                            <th data-field="name" data-sortable="true">@Html.DisplayNameFor(model => model.Name) </th>
                            <th data-field="country" data-sortable="true">@Html.DisplayNameFor(model => model.Country) </th>
                            <th data-field="address" data-sortable="true">@Html.DisplayNameFor(model => model.Address) </th>
                            <th data-field="mobile" data-sortable="true">@Html.DisplayNameFor(model => model.Mobile) </th>
                            <th data-field="email" data-sortable="true">@Html.DisplayNameFor(model => model.Email) </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.Name) </td>
                                <td>@Html.DisplayFor(modelItem => item.Country)</td>
                                <td>@Html.DisplayFor(modelItem => item.Address) </td>
                                <td>@Html.DisplayFor(modelItem => item.Mobile)</td>
                                <td>@Html.DisplayFor(modelItem => item.Email) </td>
                                <td>
                                    <a href="@Url.Action("Detail", "Buyers", new { id = item.Id })" class="btn btn-info btn-sm"><i class="fa fa-edit"></i></a> |
                                    <a href="@Url.Action("Delete", "Buyers", new { id = item.Id })" class="btn btn-danger btn-sm"><i class="fa fa-trash-alt"></i></a>

                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div> <!-- end card-box-->
        </div> <!-- end col-->
    </div>
</div>